server:
  port: 9999

spring:
  application:
    name: rinha-router-mvc
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rinha-mvc}
    username: ${POSTGRES_USER:rinha}
    password: ${POSTGRES_PASSWORD:rinha}
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true

payment:
  service:
    url:
      default: ${PAYMENT_SERVICE_URL_DEFAULT:http://localhost:8001/payments}
      fallback: ${PAYMENT_SERVICE_URL_FALLBACK:http://localhost:8002/payments}
